{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 2, "x": 6, "y": 0 }, "options": { "content": "# Raw Data" } },
  { "type": "text", "gridPos": { "h": 2, "w": 3, "x": 17, "y": 0 }, "options": { "content": "# Prink Data" } },
  {
   "title": "Energieverbrauch nach Sektor",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(primary_use) (raw_gauge_meter_reading)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energieverbrauch pro ft^2",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 7, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (raw_gauge_meter_reading/raw_gauge_square_feet)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energieverbrauch nach Sektor",
   "type": "stat",
   "gridPos": { "h": 11, "w": 7, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(primary_use) (prink_gauge_meter_reading)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energieverbrauch pro ft^2",
   "type": "stat",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prink_gauge_meter_reading/prink_gauge_square_feet)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kumulativer Energieverbrauch nach Sektor",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(primary_use) (raw_gauge_meter_reading)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Historischer Energieverbrauch nach Sektor",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum by(primary_use) (prink_gauge_meter_reading)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kumulativer Energieverbrauch nach Sektor",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(primary_use) (raw_gauge_meter_reading)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kumulativer Energieverbrauch nach Sektor",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(primary_use) (prink_gauge_meter_reading)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energieverbrauch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(primary_use) (raw_gauge_meter_reading{primary_use=\"Education\"})",
     "legendFormat": "Education"
    }
   ]
  },
  {
   "title": "Energieverbrauch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(primary_use) (prink_gauge_meter_reading{primary_use=\"Education\"})",
     "legendFormat": "Education"
    }
   ]
  },
  {
   "title": "Energieverbrauch pro Building-ID: Education",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raw_gauge_meter_reading{primary_use=\"Education\"}",
     "legendFormat": "{{building_id}}"
    }
   ]
  },
  {
   "title": "Energieverbrauch pro Building-ID: Education",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prink_gauge_meter_reading{primary_use=\"Education\"}",
     "legendFormat": "{{building_id}}"
    }
   ]
  }
 ]
}