{
 "title": "New dashboard",
 "time": { "from": "2024-07-29T12:18:30.126Z", "to": "2024-07-29T17:59:47.595Z" },
 "templating": {
  "list": [
   { "name": "k", "query": { "query": "label_values(k)" } },
   { "name": "l", "query": { "query": "label_values(l)" } },
   { "name": "delta", "query": { "query": "label_values(delta)" } },
   { "name": "run_id", "query": { "query": "label_values(run_id)" } },
   { "name": "beta", "query": { "query": "label_values(beta)" } },
   { "name": "mu", "query": { "query": "label_values(mu)" } },
   { "name": "zeta", "query": { "query": "label_values(zeta)" } }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 3, "x": 5, "y": 0 }, "options": { "content": "# Raw Data" } },
  { "type": "text", "gridPos": { "h": 2, "w": 3, "x": 17, "y": 0 }, "options": { "content": "# Prink Data" } },
  {
   "title": "Energieverbrauch Gesamt",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(raw_gauge_meter_reading{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energieverbrauch pro ft^2",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (raw_gauge_meter_reading{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\"}[1h]/raw_gauge_square_feet{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energieverbrauch Gesamt",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prink_gauge_meter_reading{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energieverbrauch pro ft^2",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (prink_gauge_meter_reading{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\"}[1h]/prink_gauge_square_feet{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energieverbrauch nach Sektor",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(primary_use) (raw_gauge_meter_reading{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energieverbrauch nach Sektor",
   "type": "stat",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(primary_use) (prink_gauge_meter_reading{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kumulativer Energieverbrauch nach Sektor",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum by(primary_use) (raw_gauge_meter_reading{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Historischer Energieverbrauch nach Sektor",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum by(primary_use) (prink_gauge_meter_reading{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kumulativer Energieverbrauch nach Sektor",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(primary_use) (raw_gauge_meter_reading{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kumulativer Energieverbrauch nach Sektor",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(primary_use) (prink_gauge_meter_reading{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "#Immobilien pro Sektor",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(primary_use) (raw_gauge_meter_reading{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "#Immobilien Gesamt",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(raw_gauge_meter_reading{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "#Immobilien pro Sektor",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(primary_use) (prink_gauge_meter_reading{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "#Immobilien Gesamt",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(prink_gauge_meter_reading{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 5, "x": 10, "y": 49 }, "options": { "content": "# >>> Sektor: Education <<<" } },
  {
   "title": "Energieverbrauch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(primary_use) (raw_gauge_meter_reading{primary_use=\"Education\"}[1h])",
     "legendFormat": "Education"
    }
   ]
  },
  {
   "title": "Energieverbrauch",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(primary_use) (prink_gauge_meter_reading{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\",primary_use=\"Education\"}[1h])",
     "legendFormat": "Education"
    }
   ]
  },
  {
   "title": "Energieverbrauch pro Building-ID: Education",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "raw_gauge_meter_reading{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\",primary_use=\"Education\"}[1h]",
     "legendFormat": "{{building_id}}"
    }
   ]
  },
  {
   "title": "Energieverbrauch pro Building-ID: Education",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prink_gauge_meter_reading{k=\"$k\",delta=\"$delta\",l=\"$l\",beta=\"$beta\",zeta=\"$zeta\",mu=\"$mu\",run_id=\"$run_id\",primary_use=\"Education\"}[1h]",
     "legendFormat": "{{building_id}}"
    }
   ]
  }
 ]
}